---
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-2:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-3:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                               cub kafka-ready -b localhost:19092 1 20 && \
                               kafka-topics --create --if-not-exists --zookeeper localhost:22181 --partitions 3 --replication-factor 1 --topic issued-token-topic && \
                               kafka-topics --create --if-not-exists --zookeeper localhost:22181 --partitions 3 --replication-factor 1 --topic used-token-topic && \
                               kafka-topics --create --if-not-exists --zookeeper localhost:22181 --partitions 3 --replication-factor 1 --topic work-request-topic && \
                               kafka-topics --create --if-not-exists --zookeeper localhost:22181 --partitions 1 --replication-factor 1 --topic work-done-topic && \
                               echo Waiting 20 seconds for Connect to be ready... && \
                               sleep 5'"
    environment:
      # The following settings are listed here only to satisfy the image's requirements.
      # We override the image's `command` anyways, hence this container will not start a broker.
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

  issuer:
    network_mode: host
    build:
      context: issuer/
      dockerfile: Dockerfile
    ports:
      - 48090:48090
    extra_hosts:
      - "moby:127.0.0.1"
    depends_on:
      - kafka-setup

  consumer1:
    network_mode: host
    build:
      context: consumer/
      dockerfile: Dockerfile
      args:
        PROPS: props/consumer1.properties
    depends_on:
      - kafka-setup
      - issuer
    volumes:
      - /home/aliashenko/workspace/tokenConsumtionPoc/props:/props:rw
    extra_hosts:
      - "moby:127.0.0.1"

  consumer2:
    network_mode: host
    build:
      context: consumer/
      dockerfile: Dockerfile
      args:
        PROPS: props/consumer2.properties
    depends_on:
      - kafka-setup
      - issuer
    volumes:
      - /home/aliashenko/workspace/tokenConsumtionPoc/props:/props:rw
    extra_hosts:
      - "moby:127.0.0.1"

  consumer3:
    network_mode: host
    build:
      context: consumer/
      dockerfile: Dockerfile
      args:
        PROPS: props/consumer3.properties
    depends_on:
      - kafka-setup
      - issuer
    volumes:
      - /home/aliashenko/workspace/tokenConsumtionPoc/props:/props:rw
    extra_hosts:
      - "moby:127.0.0.1"
